name: Release go extras
on:
  release:
    types: [created]


jobs:
  release:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.RELEASER_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: 1.18
          project_path: cmd/chain-bench
          binary_name: chain-bench
          sha256sum: true
          md5sum: true
